### ISSUE TITLE
README.md -- Installation instructions need help

### ISSUE THREAD

**Issue by androclus** [gauteh/gmailieer#38] opened 2017-08-29 19:30 UTC
I found the README.md insufficient to help me do a normal install of gmailieer.

Here are the problems I encountered, along with some suggestions for solutions.  I don't have all the solutions, though, because I simply got blocked, and don't know the answer.

1. In the requirements section of the README.me, it is unclear what these names are.  Are they pip packages? .deb's or .rpm's? Also, setup.py will not run without setuptools, which is not mentioned. So:
  a. add setuptools to the requirements list as the 6th item:

> * `setuptools`

  b. Give explicit examples as to how these requirements may actually be met. For instance, add the following text:

> In Debian 9 ("Stretch"), for instance, these prerequisites can be obtained this way:
> ```sh
> $ sudo apt-get -y install python3-tqdm python3-googleapi python3-oauth2client python3-notmuch python3-setuptools
> ```

2. "cart before horse"? -- notmuch seems to be required *before* running.
In the installation section, item 2 seems to assume that one already has a ~/.mail/[account].gmail/.notmuch directory set up.  (I only this having worked with notmuch already.  But I would have been greatly confused as a newbie, if I had not. I would have had NO idea what this even means.)  But the instructions to create a .notmuch subdir do not exist here, and are only implied.  Also, the instructions do not say that what they are really referring to is ~/.mail/[account].gmail/.notmuch/hooks/post-new .  They also apparently refer to ~/.notmuch-config , and assume the ~/.notmuch-config is already set up and pointing to ~/.mail/[account].gmail -- But again, this is not stated, and if I had not already worked with notmuch, I would not have known this.  I would have been completely lost.

3. Even setting up a ~/.notmuch-config and pointing it to ~/.mail/[account].gmail , and setting up a ~/.mail/[account].gmail/.notmuch/hooks/post-new script: When I cd to ~/.mail/[account].gmail, and run,
```
gmi init [account]@gmail
```
as per the instructions, I get:
```
A Xapian exception occurred opening database: Couldn't stat '/home/[me]/.mail/[account].gmail/.notmuch/xapian'
```
So, what?  gmailieer expects notmuch to already have been run?  How is that possible, when the maildir is not yet downloaded?

(I have no solution for this. I am stuck.)

4. If I try to run
```
gmi init [account]@gmail
```
a second time, now I get a different error message:
```
lieer.local.RepositoryException: '.gmailieer.json' exists: this repository seems to already be set up!
```
(and if I remove this, I get a similar message for the 'mail' subdir previously created.)

5. Also, the README.md needs to make it clear whether it is able to work with a previously-existing maildir or not.  And whether offlineimap or mbsync may be assumed. In another issue, it appears to be no for both of these.  If that is the case, this should be made explicit in the README.md. (Although that is too bad, because it means having do re-download all my emails.)

But if a previously-existing maildir may not be used, then how is it that it is assumed that notmuch is already installed and its database initialized?

---

In the end, the README.md installation instructions simply do not work for me. I am dead in the water.  I have spent all morning on it and tried to add some possible solutions, but I think really the best solution is that you run an actual test installation yourself from a virgin system and document it, step by step, in the README.md, so that the instructions actually work.  I would do this for you (with a fork) but I myself cannot figure out what you wanted.

Hope this helps.

**Comment by gauteh** [comment] 2017-08-29 19:46
Hi Jeff, I'm sorry that the instructions did not work for you - unfortunately I don't have time to give you a long answer at the moment, but here goes:

setuptools setup.py is a standard packaging tool for python packages, so I did not intend to give an explanation of how to use it. You can use it to create a package, distribution, source distro --- or to do a local install, that usually entails doing:

``` 
$ python setup.py build
$ python setup.py install
```

that would probably try to install gmaileer to __/usr/local/__. Hopefully your system works with that, if not check command args to choose a different prefix. Here is the [arch linux package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gmailieer-git).

A gmaileer repository was intended to be a sub-dir of your root mail folder, __with__ notmych already set up, so:

~/mail <- root mail
~/mail/.notmuch 
~/mail/arbitrary.imap.account  <- other account, maybe synced with offlineimap
~/mail/gmail.account1 <- first gmaileer repo
~/mail/gmail.account2 <- second gmaileer repo

this is an equivalent setup to mine. Then all __gmi__ commands should be run from within the ~/mail/gmail.account1 (and/or ~/mail/gmail.account2). 

The requirements names are the most generic package names I could find - irrespective of distro: specific distro instructions could go in a separate section or wiki.

**Comment by gauteh** [comment] 2017-08-29 19:50
It is not used with offlineimap or any other syncing: only notmuch. The emails have to be re-downloaded, anything else would be really tricky to do. Initial sync might take some time, but if it crashes for some reason (e.g. broken connection) it will pick up were it left if you restart it.

**Comment by androclus** [comment] 2017-08-29 20:25
Hi, Gaute - Thanks for your quick responses. Sticking to the main point of where I am stuck: How can notmuch be set up already, when the maildir does not yet exist?  As I mentioned in 3., gmi bums out because notmuch does not yet have a Xapian directory set up.  But how can I set up a notmuch installation (with its ./xapian subdir) if there is nothing for notmuch to run on yet (because the maildir has not yet been downloaded)?  This seems like a bit of a Catch-22.

**Comment by gauteh** [comment] 2017-08-29 20:29
Jeff Stern writes on august 29, 2017 22:25:
> Hi, Gaute - Thanks for your quick responses. Sticking to the main point of where I am stuck: How can notmuch be set up already, when the maildir does not yet exist?  As I mentioned in 3., gmi bums out because notmuch does not yet have a Xapian directory set up.  But how can I set up a notmuch installation (with its ./xapian subdir) if there is nothing for notmuch to run on yet (because the maildir has not yet been downloaded)?  This seems like a bit of a Catch-22.

No, notmuch does not need to have anything to work on. It can use an 
empty root, I don't have the chance to test this now, but for a fresh 
install I think this should work (backup you mail!):

$ cd ~
$ mkdir mail
$ notmuch setup
...
> follow instructions, point notmuch to ~/mail
...
$ cd mail
$ mkdir gmail.account1
$ cd gmail.account1
$ gmi init youraccount@gmail.com

**Comment by androclus** [comment] 2017-08-29 21:28
Okay, thanks.  This has gotten me farther, and I didn't realize I could do a notmuch new without any mail in there (thus creating the xapian subdir), but it does work.

I have started the download successfully! Thank you for your tips.

If it will be helpful, I've forked off this repo, and will edit the README.md to add in these steps explicitly, and send you a pull request. Should make it a bit easier for newbs like me. :-)

**Comment by gauteh** [comment] 2017-08-30 07:04
Jeff Stern writes on august 29, 2017 23:28:
> Okay, thanks.  This has gotten me farther, and I didn't realize I could do a notmuch new without any mail in there (thus creating the xapian subdir), but it does work.
> 
> I have started the download successfully! Thank you for your tips.
> 
> If it will be helpful, I've forked off this repo, and will edit the README.md to add in these steps explicitly, and send you a pull request. Should make it a bit easier for newbs like me. :-)

Yes, feel free to do that, that would be useful. As I mentioned; 
distribution-specific instructions should go in the wiki - but it would 
be fine to link to a general page from the README.

Can we close #37 as a duplicate of this?

**Closed** 2017-09-22 08:20 UTC
Labels: question
